import test from 'node:test'; import assert from 'node:assert/strict';
import { readJson, writeJson, stagedWrite, CORE_STORAGE_KEY, ENTERPRISE_STORAGE_KEY, PersistenceError } from '../lib/local-persistence.mjs';
import { readFinancialJournal, writeFinancialJournal, pruneFinancialJournal, startJournal, completeJournal, FINANCIAL_JOURNAL_KEY } from '../lib/financial-journal.mjs';
import { acquireWriterLock, assertWriter } from '../lib/single-writer.mjs';
import { createBackupEnvelope, validateBackupEnvelope, restoreBackupAtomically, SYSTEM_EVENTS_KEY } from '../lib/backup-domain.mjs';

class MemoryStorage { constructor(){this.map=new Map();this.failAt=Infinity;this.writes=0;} get length(){return this.map.size} key(i){return [...this.map.keys()][i]??null} getItem(k){return this.map.has(k)?this.map.get(k):null} setItem(k,v){this.writes++;if(this.writes===this.failAt){const e=new Error('full');e.name='QuotaExceededError';throw e}this.map.set(k,String(v))} removeItem(k){this.map.delete(k)} clear(){this.map.clear()} }
const coreData=()=>({products:[],categories:[],orders:[],shifts:[],employees:[],ledgerEntries:[],expenses:[],auditEvents:[],users:[{id:'u1'}],devices:[],cashMovements:[],settings:{restaurantName:'Falah'},currentUserId:'u1'});
const enterprise=()=>Object.fromEntries(['treasuryAccounts','treasuryMovements','cashHandovers','suppliers','supplierLedger','purchases','inventoryItems','stockMovements','payrollRuns','payrollLines','leaveRequests','taxRules','businessDays','drivers','deliveries','diningTables'].map(k=>[k,[]]));
const backup=()=>createBackupEnvelope({core:{version:2,savedAt:'x',data:coreData()},enterprise:enterprise(),appVersion:'test'});

test('PERSIST-001 corrupt Core JSON does not silently load seed state',()=>{const s=new MemoryStorage();s.setItem(CORE_STORAGE_KEY,'{');assert.throws(()=>readJson(s,CORE_STORAGE_KEY),PersistenceError)});
test('PERSIST-002 corrupt Enterprise JSON does not silently load seed state',()=>{const s=new MemoryStorage();s.setItem(ENTERPRISE_STORAGE_KEY,'no');assert.throws(()=>readJson(s,ENTERPRISE_STORAGE_KEY),PersistenceError)});
test('PERSIST-003 quota failure causes command failure rather than false success',()=>{const s=new MemoryStorage();s.failAt=1;assert.throws(()=>writeJson(s,'money',{amount:1}),e=>e.code==='QUOTA');assert.equal(s.getItem('money'),null)});
test('JRN-001 pending journal entries are never pruned',()=>{const pending=Array.from({length:20},(_,i)=>({operationId:`p${i}`,idempotencyKey:`p${i}`,kind:'sale',status:'pending',createdAt:String(i)}));assert.equal(pruneFinancialJournal([...pending,...Array.from({length:20},(_,i)=>({operationId:`c${i}`,idempotencyKey:`c${i}`,kind:'sale',status:'complete',createdAt:String(i)}))],3).filter(x=>x.status==='pending').length,20)});
test('JRN-002 completed old entries can be pruned safely',()=>{const items=Array.from({length:10},(_,i)=>({operationId:`c${i}`,idempotencyKey:`c${i}`,kind:'sale',status:'complete',createdAt:String(i).padStart(2,'0')}));assert.deepEqual(pruneFinancialJournal(items,2).map(x=>x.idempotencyKey),['c9','c8'])});
test('JRN-003 corrupt journal triggers recovery state',()=>{const s=new MemoryStorage();s.setItem(FINANCIAL_JOURNAL_KEY,'{bad');assert.throws(()=>readFinancialJournal(s),e=>e.code==='CORRUPT')});
for(const [id,kind] of [['JRN-004','sale'],['JRN-005','expense'],['JRN-006','purchase'],['JRN-007','owner_deposit']]) test(`${id} ${kind} recovery remains idempotent`,()=>{const s=new MemoryStorage();const e={operationId:id,idempotencyKey:id,kind};assert.equal(startJournal(s,e),true);assert.equal(startJournal(s,e),false);completeJournal(s,id,{movement:{id:id}});assert.equal(readFinancialJournal(s).filter(x=>x.idempotencyKey===id).length,1)});
test('TAB-001 second writer instance cannot perform financial writes',()=>{const s=new MemoryStorage();assert.equal(acquireWriterLock(s,'one',100,100),true);assert.equal(acquireWriterLock(s,'two',101,100),false);assert.throws(()=>assertWriter(s,'two',101))});
test('BAK-001 valid current backup round-trip succeeds',()=>{const s=new MemoryStorage();const b=backup();restoreBackupAtomically(s,b);assert.deepEqual(JSON.parse(s.getItem(ENTERPRISE_STORAGE_KEY)),b.enterprise);assert.equal(JSON.parse(s.getItem(CORE_STORAGE_KEY)).data.currentUserId,null)});
test('BAK-002 invalid schema is rejected',()=>assert.throws(()=>validateBackupEnvelope({backupVersion:4})));
test('BAK-003 Core-only legacy backup cannot silently mix with current Enterprise',()=>assert.throws(()=>validateBackupEnvelope({version:2,data:coreData()}),/قديمة/));
test('BAK-004 failed staged write leaves original state unchanged',()=>{const s=new MemoryStorage();s.setItem('a','"old-a"');s.setItem('b','"old-b"');s.failAt=s.writes+5;assert.throws(()=>stagedWrite(s,[{key:'a',value:'new-a'},{key:'b',value:'new-b'}]));assert.equal(s.getItem('a'),'"old-a"');assert.equal(s.getItem('b'),'"old-b"')});
test('BAK-005 invalid current user after restore requires login',()=>{const s=new MemoryStorage();const result=restoreBackupAtomically(s,backup());assert.equal(result.requiresLogin,true);assert.equal(JSON.parse(s.getItem(CORE_STORAGE_KEY)).data.currentUserId,null)});
test('BAK-006 restore event remains auditable',()=>{const s=new MemoryStorage();restoreBackupAtomically(s,backup());assert.equal(JSON.parse(s.getItem(SYSTEM_EVENTS_KEY))[0].type,'restore_success')});
