import {
  Category,
  Product,
  Employee,
  EmployeeLedgerEntry,
  User,
  Shift,
  Order,
  GrillTicket,
  Expense,
  CashMovement,
  AttendanceRecord,
  AuditEvent,
  Device,
  SystemSettings,
  NotificationItem,
} from './types';

export const INITIAL_SETTINGS: SystemSettings = {
  restaurantName: 'فاتح أبو الغنية',
  subName: 'مطاعم فالح - أبو العنبة - 24 ساعة',
  address: '6 أكتوبر - الحي السابع - سنتر الأردنية',
  phone1: '01144741115',
  phone2: '01000602832',
  phoneLandline: '0238361323',
  complaintsPhone: '01112595678',
  receiptFooter: 'شكراً لزيارتكم مطاعم فالح - أبو العنبة. نسعد بخدمتكم على مدار 24 ساعة',
  overtimeHourlyRate: 25, // 25 EGP / hour as strictly specified
  deliveryFee: 20,
  currency: 'ج.م',
  cashDiscrepancyThreshold: 50,
  autoLockMinutes: 10,
  activeShiftName: 'وردية صباحية',
  printerWidth: '80mm',
  autoPrintReceipt: true,
  autoPrintPreparationTicket: true,
  numberOfReceiptCopies: 1,
  grillScreenSoundAlert: true,
};

export const INITIAL_USERS: User[] = [
  {
    id: 'u-owner',
    name: 'الحاج فالح (المالك)',
    username: 'owner',
    role: 'owner',
    pin: '1234',
    active: true,
    avatar: '👨‍💼',
    permissions: ['all'],
  },
  {
    id: 'u-manager',
    name: 'سامح عبد الله (المدير)',
    username: 'sameh_manager',
    role: 'manager',
    pin: '5555',
    active: true,
    avatar: '👔',
    permissions: [
      'pos',
      'orders_view',
      'orders_cancel',
      'orders_refund',
      'orders_discount',
      'shifts_manage',
      'shifts_blind_close',
      'cash_drawer',
      'expenses_add',
      'employees_manage',
      'employees_ledger',
      'attendance_manage',
      'menu_manage',
      'reports_view',
      'control_center',
      'audit_view',
      'devices_manage',
      'treasury_manage',
      'business_day_close',
      'business_day_open',
      'cash_count',
      'safe_drop',
      'delivery_manage',
      'delivery_override',
      'delivery_settlement_approve',
      'purchasing_manage',
      'suppliers_manage',
      'users_manage',
      'settings_manage',
    ],
  },
  {
    id: 'u-cashier-ahmed',
    name: 'أحمد صبحي (كاشير)',
    username: 'ahmed_pos',
    role: 'cashier',
    pin: '1111',
    active: true,
    avatar: '🧑‍💻',
    permissions: ['pos', 'orders_view', 'shifts_blind_close', 'cash_drawer_sale'],
  },
  {
    id: 'u-grill-ibrahim',
    name: 'إبراهيم شواية (محطة الفحم)',
    username: 'grill_ibrahim',
    role: 'grill',
    pin: '2222',
    active: true,
    avatar: '👨‍🍳',
    permissions: ['grill_only'],
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-sandwiches-faleh', name: 'ساندوتشات فالح', sortOrder: 1, active: true, icon: '🥪' },
  { id: 'cat-sandwiches-meat', name: 'ساندوتشات اللحوم', sortOrder: 2, active: true, icon: '🥩' },
  { id: 'cat-grills', name: 'مشويات فالح', sortOrder: 3, active: true, icon: '🍗' },
  { id: 'cat-meals', name: 'وجبات فالح', sortOrder: 4, active: true, icon: '🍱' },
  { id: 'cat-plates', name: 'أطباق فالح', sortOrder: 5, active: true, icon: '🥗' },
  { id: 'cat-pastries', name: 'المعجنات', sortOrder: 6, active: true, icon: '🥟' },
  { id: 'cat-rice', name: 'الأرز', sortOrder: 7, active: true, icon: '🍚' },
  { id: 'cat-pastas', name: 'المكرونات', sortOrder: 8, active: true, icon: '🍝' },
  { id: 'cat-appetizers', name: 'المقبلات', sortOrder: 9, active: true, icon: '🥣' },
  { id: 'cat-beverages', name: 'المشروبات', sortOrder: 10, active: true, icon: '🥤' },
];

export const INITIAL_PRODUCTS: Product[] = [
  // ساندوتشات فالح (صمون / صاج / فرنساوي)
  {
    id: 'p-falafel',
    name: 'ساندوتش فلافل',
    categoryId: 'cat-sandwiches-faleh',
    basePrice: 25,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 25 },
      { id: 'v-saj', name: 'صاج', price: 25 },
      { id: 'v-french', name: 'فرنساوي', price: 30 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 1,
    popular: true,
  },
  {
    id: 'p-fries',
    name: 'ساندوتش بطاطس',
    categoryId: 'cat-sandwiches-faleh',
    basePrice: 30,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 30 },
      { id: 'v-saj', name: 'صاج', price: 30 },
      { id: 'v-french', name: 'فرنساوي', price: 35 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 2,
    popular: true,
  },
  {
    id: 'p-mix',
    name: 'ساندوتش مكس',
    categoryId: 'cat-sandwiches-faleh',
    basePrice: 30,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 30 },
      { id: 'v-saj', name: 'صاج', price: 30 },
      { id: 'v-french', name: 'فرنساوي', price: 35 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 3,
  },
  {
    id: 'p-mix-faleh',
    name: 'ساندوتش مكس فالح',
    categoryId: 'cat-sandwiches-faleh',
    basePrice: 40,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 40 },
      { id: 'v-saj', name: 'صاج', price: 40 },
      { id: 'v-french', name: 'فرنساوي', price: 45 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 4,
    popular: true,
  },
  {
    id: 'p-mix-eggplant',
    name: 'ساندوتش مكس باذنجان',
    categoryId: 'cat-sandwiches-faleh',
    basePrice: 40,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 40 },
      { id: 'v-saj', name: 'صاج', price: 40 },
      { id: 'v-french', name: 'فرنساوي', price: 45 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 5,
  },
  {
    id: 'p-fries-rumi',
    name: 'ساندوتش بطاطس رومي',
    categoryId: 'cat-sandwiches-faleh',
    basePrice: 45,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 45 },
      { id: 'v-saj', name: 'صاج', price: 45 },
      { id: 'v-french', name: 'فرنساوي', price: 50 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 6,
  },
  {
    id: 'p-fries-mozzarella',
    name: 'ساندوتش بطاطس موزاريلا',
    categoryId: 'cat-sandwiches-faleh',
    basePrice: 45,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 45 },
      { id: 'v-saj', name: 'صاج', price: 45 },
      { id: 'v-french', name: 'فرنساوي', price: 50 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 7,
  },
  {
    id: 'p-fries-cheddar',
    name: 'ساندوتش بطاطس شيدر',
    categoryId: 'cat-sandwiches-faleh',
    basePrice: 45,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 45 },
      { id: 'v-saj', name: 'صاج', price: 45 },
      { id: 'v-french', name: 'فرنساوي', price: 50 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 8,
  },
  {
    id: 'p-fries-2cheeses',
    name: 'ساندوتش بطاطس 2 نوع',
    categoryId: 'cat-sandwiches-faleh',
    basePrice: 55,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 55 },
      { id: 'v-saj', name: 'صاج', price: 55 },
      { id: 'v-french', name: 'فرنساوي', price: 60 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 9,
  },
  {
    id: 'p-fries-3cheeses',
    name: 'ساندوتش بطاطس 3 نوع',
    categoryId: 'cat-sandwiches-faleh',
    basePrice: 65,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 65 },
      { id: 'v-saj', name: 'صاج', price: 65 },
      { id: 'v-french', name: 'فرنساوي', price: 70 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 10,
  },
  {
    id: 'p-omelette-plain',
    name: 'ساندوتش أومليت سادة',
    categoryId: 'cat-sandwiches-faleh',
    basePrice: 35,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 35 },
      { id: 'v-saj', name: 'صاج', price: 35 },
      { id: 'v-french', name: 'فرنساوي', price: 35 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 11,
  },
  {
    id: 'p-omelette-cheese',
    name: 'ساندوتش أومليت جبنة',
    categoryId: 'cat-sandwiches-faleh',
    basePrice: 45,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 45 },
      { id: 'v-saj', name: 'صاج', price: 45 },
      { id: 'v-french', name: 'فرنساوي', price: 50 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 12,
  },
  {
    id: 'p-egg-pastirma',
    name: 'ساندوتش بيض بسطرمة',
    categoryId: 'cat-sandwiches-faleh',
    basePrice: 50,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 50 },
      { id: 'v-saj', name: 'صاج', price: 50 },
      { id: 'v-french', name: 'فرنساوي', price: 65 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 13,
  },
  {
    id: 'p-kibbeh-sandwich',
    name: 'ساندوتش كبيبة',
    categoryId: 'cat-sandwiches-faleh',
    basePrice: 45,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 45 },
      { id: 'v-saj', name: 'صاج', price: 45 },
      { id: 'v-french', name: 'فرنساوي', price: 50 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 14,
  },
  {
    id: 'p-fried-cheese',
    name: 'ساندوتش جبنة مقلية',
    categoryId: 'cat-sandwiches-faleh',
    basePrice: 45,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 45 },
      { id: 'v-saj', name: 'صاج', price: 45 },
      { id: 'v-french', name: 'فرنساوي', price: 50 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 15,
  },
  {
    id: 'p-labneh-sandwich',
    name: 'ساندوتش لبنة',
    categoryId: 'cat-sandwiches-faleh',
    basePrice: 25,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 25 },
      { id: 'v-saj', name: 'صاج', price: 25 },
      { id: 'v-french', name: 'فرنساوي', price: 30 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 16,
  },

  // ساندوتشات اللحوم (صمون / صاج / فرنساوي)
  {
    id: 'p-kofta-sandwich',
    name: 'ساندوتش كفتة ع الفحم',
    categoryId: 'cat-sandwiches-meat',
    basePrice: 90,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 90 },
      { id: 'v-saj', name: 'صاج', price: 90 },
      { id: 'v-french', name: 'فرنساوي', price: 95 },
    ],
    isAvailable: true,
    sendToGrill: true, // يرسل للفحم
    sortOrder: 1,
    popular: true,
  },
  {
    id: 'p-kofta-mozzarella',
    name: 'ساندوتش كفتة موزاريلا',
    categoryId: 'cat-sandwiches-meat',
    basePrice: 100,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 100 },
      { id: 'v-saj', name: 'صاج', price: 100 },
      { id: 'v-french', name: 'فرنساوي', price: 105 },
    ],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 2,
  },
  {
    id: 'p-shish-sandwich',
    name: 'ساندوتش شيش طاووق',
    categoryId: 'cat-sandwiches-meat',
    basePrice: 90,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 90 },
      { id: 'v-saj', name: 'صاج', price: 90 },
      { id: 'v-french', name: 'فرنساوي', price: 100 },
    ],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 3,
    popular: true,
  },
  {
    id: 'p-shish-mozzarella',
    name: 'ساندوتش شيش موزاريلا',
    categoryId: 'cat-sandwiches-meat',
    basePrice: 100,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 100 },
      { id: 'v-saj', name: 'صاج', price: 100 },
      { id: 'v-french', name: 'فرنساوي', price: 105 },
    ],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 4,
  },
  {
    id: 'p-liver-grill',
    name: 'ساندوتش كبدة جريل',
    categoryId: 'cat-sandwiches-meat',
    basePrice: 70,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 70 },
      { id: 'v-saj', name: 'صاج', price: 70 },
      { id: 'v-french', name: 'فرنساوي', price: 75 },
    ],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 5,
  },
  {
    id: 'p-burger',
    name: 'ساندوتش برجر',
    categoryId: 'cat-sandwiches-meat',
    basePrice: 80,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 80 },
      { id: 'v-saj', name: 'صاج', price: 80 },
      { id: 'v-french', name: 'فرنساوي', price: 85 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 6,
  },
  {
    id: 'p-burger-cheese',
    name: 'ساندوتش برجر جبنة',
    categoryId: 'cat-sandwiches-meat',
    basePrice: 90,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 90 },
      { id: 'v-saj', name: 'صاج', price: 90 },
      { id: 'v-french', name: 'فرنساوي', price: 95 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 7,
  },
  {
    id: 'p-burger-egg',
    name: 'ساندوتش برجر بيض',
    categoryId: 'cat-sandwiches-meat',
    basePrice: 90,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 90 },
      { id: 'v-saj', name: 'صاج', price: 90 },
      { id: 'v-french', name: 'فرنساوي', price: 95 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 8,
  },
  {
    id: 'p-burger-king',
    name: 'ساندوتش برجر كينج',
    categoryId: 'cat-sandwiches-meat',
    basePrice: 100,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 100 },
      { id: 'v-saj', name: 'صاج', price: 100 },
      { id: 'v-french', name: 'فرنساوي', price: 105 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 9,
  },
  {
    id: 'p-pane',
    name: 'ساندوتش بانيه',
    categoryId: 'cat-sandwiches-meat',
    basePrice: 90,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 90 },
      { id: 'v-saj', name: 'صاج', price: 90 },
      { id: 'v-french', name: 'فرنساوي', price: 95 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 10,
    popular: true,
  },
  {
    id: 'p-pane-cheese',
    name: 'ساندوتش بانيه جبنة',
    categoryId: 'cat-sandwiches-meat',
    basePrice: 100,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 100 },
      { id: 'v-saj', name: 'صاج', price: 100 },
      { id: 'v-french', name: 'فرنساوي', price: 105 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 11,
  },
  {
    id: 'p-crispy',
    name: 'ساندوتش كريسبي',
    categoryId: 'cat-sandwiches-meat',
    basePrice: 90,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 90 },
      { id: 'v-saj', name: 'صاج', price: 90 },
      { id: 'v-french', name: 'فرنساوي', price: 95 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 12,
  },
  {
    id: 'p-zinger',
    name: 'ساندوتش زنجر',
    categoryId: 'cat-sandwiches-meat',
    basePrice: 90,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 90 },
      { id: 'v-saj', name: 'صاج', price: 90 },
      { id: 'v-french', name: 'فرنساوي', price: 95 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 13,
  },
  {
    id: 'p-mexican',
    name: 'ساندوتش مكسيكان',
    categoryId: 'cat-sandwiches-meat',
    basePrice: 70,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 70 },
      { id: 'v-saj', name: 'صاج', price: 70 },
      { id: 'v-french', name: 'فرنساوي', price: 75 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 14,
  },
  {
    id: 'p-fajita',
    name: 'ساندوتش فاهيتا',
    categoryId: 'cat-sandwiches-meat',
    basePrice: 90,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 90 },
      { id: 'v-saj', name: 'صاج', price: 90 },
      { id: 'v-french', name: 'فرنساوي', price: 95 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 15,
  },
  {
    id: 'p-egg-meat',
    name: 'ساندوتش بيض باللحمة',
    categoryId: 'cat-sandwiches-meat',
    basePrice: 75,
    variants: [
      { id: 'v-samoon', name: 'صمون', price: 75 },
      { id: 'v-saj', name: 'صاج', price: 75 },
      { id: 'v-french', name: 'فرنساوي', price: 80 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 16,
  },

  // مشويات فالح (تشمل سلطة + خبز) - All sent to grill
  {
    id: 'p-quarter-chicken-thigh',
    name: 'ربع فرخة وراك (مشوي)',
    categoryId: 'cat-grills',
    basePrice: 100,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 1,
    popular: true,
    notes: 'تشمل سلطة + خبز',
  },
  {
    id: 'p-quarter-chicken-breast',
    name: 'ربع فرخة صدور (مشوي)',
    categoryId: 'cat-grills',
    basePrice: 120,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 2,
    notes: 'تشمل سلطة + خبز',
  },
  {
    id: 'p-half-chicken',
    name: 'نص فرخة مشوية ع الفحم',
    categoryId: 'cat-grills',
    basePrice: 165,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 3,
    popular: true,
    notes: 'تشمل سلطة + خبز',
  },
  {
    id: 'p-half-chicken-shish',
    name: 'نص فرخة شيش مشوي',
    categoryId: 'cat-grills',
    basePrice: 170,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 4,
    notes: 'تشمل سلطة + خبز',
  },
  {
    id: 'p-half-chicken-musahab',
    name: 'نص فرخة مسحب ع الفحم',
    categoryId: 'cat-grills',
    basePrice: 170,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 5,
    notes: 'تشمل سلطة + خبز',
  },
  {
    id: 'p-quarter-kg-kofta',
    name: 'ربع كيلو كفتة مشوية',
    categoryId: 'cat-grills',
    basePrice: 150,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 6,
    popular: true,
    notes: 'تشمل سلطة + خبز',
  },
  {
    id: 'p-half-kg-kofta',
    name: 'نص كيلو كفتة مشوية',
    categoryId: 'cat-grills',
    basePrice: 300,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 7,
    notes: 'تشمل سلطة + خبز',
  },
  {
    id: 'p-1kg-kofta',
    name: 'كيلو كفتة مشوية ع الفحم',
    categoryId: 'cat-grills',
    basePrice: 600,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 8,
    notes: 'تشمل سلطة + خبز',
  },
  {
    id: 'p-quarter-kg-shish',
    name: 'ربع كيلو شيش طاووق',
    categoryId: 'cat-grills',
    basePrice: 150,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 9,
    notes: 'تشمل سلطة + خبز',
  },
  {
    id: 'p-half-kg-shish',
    name: 'نص كيلو شيش طاووق',
    categoryId: 'cat-grills',
    basePrice: 300,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 10,
    notes: 'تشمل سلطة + خبز',
  },
  {
    id: 'p-1kg-shish',
    name: 'كيلو شيش طاووق ع الفحم',
    categoryId: 'cat-grills',
    basePrice: 600,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 11,
    notes: 'تشمل سلطة + خبز',
  },
  {
    id: 'p-whole-musahab',
    name: 'فرخة مسحب كاملة',
    categoryId: 'cat-grills',
    basePrice: 350,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 12,
    notes: 'تشمل سلطة + خبز',
  },
  {
    id: 'p-whole-charcoal',
    name: 'فرخة فحم كاملة',
    categoryId: 'cat-grills',
    basePrice: 340,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 13,
    popular: true,
    notes: 'تشمل سلطة + خبز',
  },
  {
    id: 'p-whole-shish',
    name: 'فرخة شيش كاملة',
    categoryId: 'cat-grills',
    basePrice: 345,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 14,
    notes: 'تشمل سلطة + خبز',
  },

  // وجبات فالح (تشمل أرز + بطاطس + سلطة + خبز)
  {
    id: 'p-meal-econ-thigh',
    name: 'وجبة اقتصادية ورك',
    categoryId: 'cat-meals',
    basePrice: 110,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 1,
    popular: true,
    notes: 'تشمل أرز + بطاطس + سلطة + خبز',
  },
  {
    id: 'p-meal-econ-breast',
    name: 'وجبة اقتصادية صدر',
    categoryId: 'cat-meals',
    basePrice: 140,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 2,
    notes: 'تشمل أرز + بطاطس + سلطة + خبز',
  },
  {
    id: 'p-meal-kabsa',
    name: 'وجبة كبسة',
    categoryId: 'cat-meals',
    basePrice: 190,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 3,
    notes: 'تشمل أرز + بطاطس + سلطة + خبز',
  },
  {
    id: 'p-meal-family',
    name: 'وجبة عائلية فالح',
    categoryId: 'cat-meals',
    basePrice: 380,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 4,
    notes: 'وجبة تكفي العائلة',
  },
  {
    id: 'p-meal-family-musahab',
    name: 'وجبة عائلية مسحب',
    categoryId: 'cat-meals',
    basePrice: 390,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 5,
  },
  {
    id: 'p-meal-musahab',
    name: 'وجبة مسحب فالح',
    categoryId: 'cat-meals',
    basePrice: 200,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 6,
  },
  {
    id: 'p-meal-family-shish',
    name: 'وجبة عائلية شيش',
    categoryId: 'cat-meals',
    basePrice: 385,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 7,
  },
  {
    id: 'p-meal-kabsa-shish',
    name: 'وجبة كبسة شيش',
    categoryId: 'cat-meals',
    basePrice: 195,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 8,
  },
  {
    id: 'p-meal-saver-thigh',
    name: 'وجبة موفرة ورك',
    categoryId: 'cat-meals',
    basePrice: 170,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 9,
  },
  {
    id: 'p-meal-saver-breast',
    name: 'وجبة موفرة صدر',
    categoryId: 'cat-meals',
    basePrice: 180,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 10,
  },
  {
    id: 'p-meal-kofta',
    name: 'وجبة كفتة مشوية',
    categoryId: 'cat-meals',
    basePrice: 170,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 11,
    popular: true,
  },
  {
    id: 'p-meal-shish',
    name: 'وجبة شيش طاووق',
    categoryId: 'cat-meals',
    basePrice: 170,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 12,
    popular: true,
  },
  {
    id: 'p-meal-shish-kofta',
    name: 'وجبة شيش + كفتة',
    categoryId: 'cat-meals',
    basePrice: 170,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 13,
    popular: true,
  },
  {
    id: 'p-meal-mixgrill-thigh',
    name: 'وجبة ميكس جريل ورك',
    categoryId: 'cat-meals',
    basePrice: 220,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 14,
  },
  {
    id: 'p-meal-mixgrill-breast',
    name: 'وجبة ميكس جريل صدر',
    categoryId: 'cat-meals',
    basePrice: 230,
    variants: [],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 15,
  },
  {
    id: 'p-meal-pane',
    name: 'وجبة بانيه فراخ',
    categoryId: 'cat-meals',
    basePrice: 170,
    variants: [],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 16,
  },
  {
    id: 'p-meal-crispy',
    name: 'وجبة كرسبي فراخ',
    categoryId: 'cat-meals',
    basePrice: 170,
    variants: [],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 17,
  },
  {
    id: 'p-meal-zinger',
    name: 'وجبة زنجر حار',
    categoryId: 'cat-meals',
    basePrice: 175,
    variants: [],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 18,
  },
  {
    id: 'p-meal-fajita',
    name: 'وجبة فاهيتا',
    categoryId: 'cat-meals',
    basePrice: 170,
    variants: [],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 19,
  },

  // أطباق فالح (صغير / وسط / كبير)
  {
    id: 'p-plate-falafel',
    name: 'طبق فلافل 5 حبات',
    categoryId: 'cat-plates',
    basePrice: 5,
    variants: [
      { id: 'v-small', name: 'صغير (5 حبات)', price: 5 },
      { id: 'v-med', name: 'وسط (10 حبات)', price: 10 },
      { id: 'v-large', name: 'كبير (15 حبة)', price: 15 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 1,
  },
  {
    id: 'p-plate-fries',
    name: 'طبق بطاطس',
    categoryId: 'cat-plates',
    basePrice: 25,
    variants: [
      { id: 'v-small', name: 'صغير', price: 25 },
      { id: 'v-med', name: 'وسط', price: 30 },
      { id: 'v-large', name: 'كبير', price: 50 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 2,
    popular: true,
  },
  {
    id: 'p-plate-omelette-plain',
    name: 'طبق أومليت سادة',
    categoryId: 'cat-plates',
    basePrice: 30,
    variants: [
      { id: 'v-small', name: 'صغير', price: 30 },
      { id: 'v-med', name: 'وسط', price: 40 },
      { id: 'v-large', name: 'كبير', price: 50 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 3,
  },
  {
    id: 'p-plate-omelette-cheese',
    name: 'طبق أومليت بالجبنة',
    categoryId: 'cat-plates',
    basePrice: 40,
    variants: [
      { id: 'v-small', name: 'صغير', price: 40 },
      { id: 'v-med', name: 'وسط', price: 45 },
      { id: 'v-large', name: 'كبير', price: 50 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 4,
  },
  {
    id: 'p-plate-egg-pastirma',
    name: 'طبق بيض بسطرمة',
    categoryId: 'cat-plates',
    basePrice: 50,
    variants: [
      { id: 'v-small', name: 'صغير', price: 50 },
      { id: 'v-med', name: 'وسط', price: 60 },
      { id: 'v-large', name: 'كبير', price: 70 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 5,
  },
  {
    id: 'p-plate-kibbeh',
    name: 'طبق كبيبة 3 قطع',
    categoryId: 'cat-plates',
    basePrice: 75,
    variants: [],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 6,
  },
  {
    id: 'p-plate-eggplant',
    name: 'طبق باذنجان',
    categoryId: 'cat-plates',
    basePrice: 15,
    variants: [
      { id: 'v-small', name: 'صغير', price: 15 },
      { id: 'v-med', name: 'وسط', price: 25 },
      { id: 'v-large', name: 'كبير', price: 30 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 7,
  },
  {
    id: 'p-plate-fries-cheese',
    name: 'طبق بطاطس بالجبنة',
    categoryId: 'cat-plates',
    basePrice: 45,
    variants: [
      { id: 'v-small', name: 'صغير', price: 45 },
      { id: 'v-med', name: 'وسط', price: 55 },
      { id: 'v-large', name: 'كبير', price: 60 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 8,
  },
  {
    id: 'p-plate-liver',
    name: 'طبق كبدة جريل',
    categoryId: 'cat-plates',
    basePrice: 70,
    variants: [
      { id: 'v-med', name: 'وسط', price: 70 },
      { id: 'v-large', name: 'كبير', price: 120 },
    ],
    isAvailable: true,
    sendToGrill: true,
    sortOrder: 9,
  },
  {
    id: 'p-plate-labneh',
    name: 'طبق لبنة',
    categoryId: 'cat-plates',
    basePrice: 25,
    variants: [
      { id: 'v-small', name: 'صغير', price: 25 },
      { id: 'v-med', name: 'وسط', price: 35 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 10,
  },

  // المعجنات
  {
    id: 'p-pastry-white-cheese',
    name: 'فطيرة جبنة بيضة',
    categoryId: 'cat-pastries',
    basePrice: 15,
    variants: [],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 1,
  },
  {
    id: 'p-pastry-rumi',
    name: 'فطيرة جبنة رومي',
    categoryId: 'cat-pastries',
    basePrice: 15,
    variants: [],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 2,
  },
  {
    id: 'p-pastry-cheddar',
    name: 'فطيرة جبنة شيدر',
    categoryId: 'cat-pastries',
    basePrice: 15,
    variants: [],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 3,
  },
  {
    id: 'p-pastry-kiri',
    name: 'فطيرة جبنة كيري',
    categoryId: 'cat-pastries',
    basePrice: 15,
    variants: [],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 4,
  },
  {
    id: 'p-pastry-sausage',
    name: 'فطيرة سوسيس',
    categoryId: 'cat-pastries',
    basePrice: 15,
    variants: [],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 5,
  },
  {
    id: 'p-pastry-spinach',
    name: 'فطيرة سبانخ',
    categoryId: 'cat-pastries',
    basePrice: 15,
    variants: [],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 6,
  },
  {
    id: 'p-pastry-zaatar',
    name: 'منقوشة زعتر',
    categoryId: 'cat-pastries',
    basePrice: 15,
    variants: [],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 7,
    popular: true,
  },
  {
    id: 'p-pastry-zaatar-labneh',
    name: 'منقوشة زعتر لبنة',
    categoryId: 'cat-pastries',
    basePrice: 20,
    variants: [],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 8,
  },
  {
    id: 'p-pastry-lahm',
    name: 'لحمة بعجين',
    categoryId: 'cat-pastries',
    basePrice: 20,
    variants: [],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 9,
    popular: true,
  },
  {
    id: 'p-pastry-musakhan',
    name: 'مسخن دجاج',
    categoryId: 'cat-pastries',
    basePrice: 50,
    variants: [],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 10,
  },

  // الأرز
  {
    id: 'p-rice',
    name: 'طبق أرز فالح المبهر',
    categoryId: 'cat-rice',
    basePrice: 40,
    variants: [
      { id: 'v-small', name: 'صغير', price: 40 },
      { id: 'v-med', name: 'وسط', price: 50 },
      { id: 'v-large', name: 'كبير', price: 60 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 1,
    popular: true,
  },

  // المكرونات
  {
    id: 'p-pasta-bechamel',
    name: 'مكرونة بشاميل',
    categoryId: 'cat-pastas',
    basePrice: 50,
    variants: [],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 1,
    popular: true,
  },
  {
    id: 'p-pasta-negresco',
    name: 'مكرونة نجرسكو فراخ',
    categoryId: 'cat-pastas',
    basePrice: 50,
    variants: [],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 2,
    popular: true,
  },

  // المقبلات
  {
    id: 'p-app-musabbaha',
    name: 'مسبحة',
    categoryId: 'cat-appetizers',
    basePrice: 25,
    variants: [],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 1,
  },
  {
    id: 'p-app-fattoush',
    name: 'فتوش بالخبز المحمص',
    categoryId: 'cat-appetizers',
    basePrice: 40,
    variants: [],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 2,
  },
  {
    id: 'p-app-tabbouleh',
    name: 'تبولة لبنانية',
    categoryId: 'cat-appetizers',
    basePrice: 45,
    variants: [],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 3,
  },
  {
    id: 'p-app-coleslaw',
    name: 'كلوسلو',
    categoryId: 'cat-appetizers',
    basePrice: 30,
    variants: [],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 4,
  },
  {
    id: 'p-app-baba-ghanoush',
    name: 'بابا غنوج',
    categoryId: 'cat-appetizers',
    basePrice: 25,
    variants: [
      { id: 'v-small', name: 'صغير', price: 25 },
      { id: 'v-large', name: 'كبير', price: 40 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 5,
  },
  {
    id: 'p-app-tahini',
    name: 'طحينة فالح',
    categoryId: 'cat-appetizers',
    basePrice: 25,
    variants: [
      { id: 'v-small', name: 'صغير', price: 25 },
      { id: 'v-large', name: 'كبير', price: 30 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 6,
  },
  {
    id: 'p-app-green-salad',
    name: 'سلطة خضرا بلدي',
    categoryId: 'cat-appetizers',
    basePrice: 25,
    variants: [
      { id: 'v-small', name: 'صغير', price: 25 },
      { id: 'v-large', name: 'كبير', price: 30 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 7,
  },
  {
    id: 'p-app-toum',
    name: 'تومية سورية',
    categoryId: 'cat-appetizers',
    basePrice: 25,
    variants: [
      { id: 'v-small', name: 'صغير', price: 25 },
      { id: 'v-large', name: 'كبير', price: 30 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 8,
    popular: true,
  },
  {
    id: 'p-app-kibbeh-piece',
    name: 'قرص كبيبة مقلي',
    categoryId: 'cat-appetizers',
    basePrice: 25,
    variants: [],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 9,
  },

  // المشروبات
  {
    id: 'p-bev-water',
    name: 'مياه معدنية صغيرة',
    categoryId: 'cat-beverages',
    basePrice: 10,
    variants: [],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 1,
    popular: true,
  },
  {
    id: 'p-bev-can',
    name: 'كانز (بيبسي / سفن / ميرندا)',
    categoryId: 'cat-beverages',
    basePrice: 20,
    variants: [
      { id: 'v-pepsi', name: 'بيبسي', price: 20 },
      { id: 'v-7up', name: 'سفن آب', price: 20 },
      { id: 'v-mirinda', name: 'ميرندا برتقال', price: 20 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 2,
    popular: true,
  },
  {
    id: 'p-bev-liter',
    name: 'مشروب غازي 1 لتر',
    categoryId: 'cat-beverages',
    basePrice: 35,
    variants: [
      { id: 'v-1l-pepsi', name: 'بيبسي 1 لتر', price: 35 },
      { id: 'v-1l-7up', name: 'سفن 1 لتر', price: 35 },
    ],
    isAvailable: true,
    sendToGrill: false,
    sortOrder: 3,
  },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    name: 'أحمد صبحي محمود',
    employeeNumber: 'EMP-101',
    jobTitle: 'كاشير أول ومسؤول خزنة',
    phone: '01123456781',
    hireDate: '2023-01-15',
    compensationType: 'daily',
    dailyWage: 250, // 250 EGP/day
    shiftValue: 250, // 250 EGP per normal shift
    pin: '1111',
    role: 'cashier',
    isActive: true,
    notes: 'كاشير الوردية الصباحية - منتظم',
  },
  {
    id: 'emp-2',
    name: 'محمد علي حسن',
    employeeNumber: 'EMP-102',
    jobTitle: 'معلم شواية وفحم',
    phone: '01098765432',
    hireDate: '2023-03-01',
    compensationType: 'daily',
    dailyWage: 300, // 300 EGP/day
    shiftValue: 300,
    pin: '2222',
    role: 'grill',
    isActive: true,
    notes: 'عليه سلفة جارية بقيمة 500 جنيه ورصيده الحالي سالب (-200 ج)',
  },
  {
    id: 'emp-3',
    name: 'محمود الشامي',
    employeeNumber: 'EMP-103',
    jobTitle: 'معلم سندوتشات صاج وصمون',
    phone: '01234567890',
    hireDate: '2023-06-10',
    compensationType: 'daily',
    dailyWage: 280,
    shiftValue: 280,
    pin: '3333',
    role: 'supervisor',
    isActive: true,
    notes: 'يشتغل تطبيقات في عطلات نهاية الأسبوع',
  },
  {
    id: 'emp-4',
    name: 'سامح عبد الله',
    employeeNumber: 'EMP-104',
    jobTitle: 'مدير الصالة والورديات',
    phone: '01001122334',
    hireDate: '2022-11-01',
    compensationType: 'monthly',
    dailyWage: 0,
    shiftValue: 350,
    monthlySalary: 8500,
    pin: '5555',
    role: 'manager',
    isActive: true,
    notes: 'صلاحيات إدارية كاملة واعتماد السلف والإلغاءات',
  },
  {
    id: 'emp-5',
    name: 'إبراهيم سيد عواد',
    employeeNumber: 'EMP-105',
    jobTitle: 'مساعد شواية وتحضير',
    phone: '01155667788',
    hireDate: '2023-09-01',
    compensationType: 'daily',
    dailyWage: 220,
    shiftValue: 220,
    pin: '4444',
    role: 'grill',
    isActive: true,
    notes: 'وردية ليلية',
  },
  {
    id: 'emp-6',
    name: 'كريم مجدي فتحي',
    employeeNumber: 'EMP-106',
    jobTitle: 'طيار توصيل (دليفري)',
    phone: '01511223344',
    hireDate: '2024-01-10',
    compensationType: 'daily',
    dailyWage: 200,
    shiftValue: 200,
    pin: '6666',
    role: 'cashier',
    isActive: true,
    notes: 'توصيل طلبات دليفري',
  },
];

export const INITIAL_LEDGER_ENTRIES: EmployeeLedgerEntry[] = [
  // أحمد صبحي: Demo scenario (Day wage 250, Advance 500, Overtime 2 hrs x 25 = 50, Withdrawal 100) -> Balance = +100 EGP
  {
    id: 'led-1',
    employeeId: 'emp-1',
    date: '2026-08-18',
    time: '08:00',
    type: 'daily_wage',
    description: 'تسجيل يومية عمل الوردية الصباحية',
    debit: 0,
    credit: 250,
    balanceAfter: 250,
    recordedBy: 'سامح عبد الله (المدير)',
  },
  {
    id: 'led-2',
    employeeId: 'emp-1',
    date: '2026-08-18',
    time: '14:00',
    type: 'advance',
    description: 'سلفة نقدية عاجلة من الخزنة',
    debit: 200,
    credit: 0,
    balanceAfter: 50,
    recordedBy: 'سامح عبد الله (المدير)',
    authorizedBy: 'الحاج فالح (المالك)',
  },
  {
    id: 'led-3',
    employeeId: 'emp-1',
    date: '2026-08-18',
    time: '17:00',
    type: 'overtime',
    description: 'ساعات إضافية (2 ساعة × 25 ج/ساعة)',
    debit: 0,
    credit: 50,
    balanceAfter: 100,
    recordedBy: 'سامح عبد الله (المدير)',
  },
  {
    id: 'led-4',
    employeeId: 'emp-1',
    date: '2026-08-19',
    time: '08:15',
    type: 'daily_wage',
    description: 'يومية عمل اليوم الحالي',
    debit: 0,
    credit: 250,
    balanceAfter: 350,
    recordedBy: 'سامح عبد الله (المدير)',
  },

  // محمد علي حسن: Demo Negative Balance Scenario (Advance 500 when 0 balance -> -500, then day wage 300 -> -200 EGP)
  {
    id: 'led-5',
    employeeId: 'emp-2',
    date: '2026-08-17',
    time: '10:00',
    type: 'advance',
    description: 'سلفة شراء مستلزمات عائلية خاصة',
    debit: 500,
    credit: 0,
    balanceAfter: -500,
    recordedBy: 'سامح عبد الله (المدير)',
    authorizedBy: 'الحاج فالح (المالك)',
  },
  {
    id: 'led-6',
    employeeId: 'emp-2',
    date: '2026-08-18',
    time: '08:00',
    type: 'daily_wage',
    description: 'تسجيل يومية عمل شواية',
    debit: 0,
    credit: 300,
    balanceAfter: -200,
    recordedBy: 'سامح عبد الله (المدير)',
  },

  // محمود الشامي: Demo Extra Shift (تطبيق) scenario
  {
    id: 'led-7',
    employeeId: 'emp-3',
    date: '2026-08-18',
    time: '08:00',
    type: 'daily_wage',
    description: 'يومية عمل صباحية',
    debit: 0,
    credit: 280,
    balanceAfter: 280,
    recordedBy: 'سامح عبد الله (المدير)',
  },
  {
    id: 'led-8',
    employeeId: 'emp-3',
    date: '2026-08-18',
    time: '20:00',
    type: 'extra_shift',
    description: 'تطبيق وردية ليلية إضافية كاملة (1 شيفت = 280 ج)',
    debit: 0,
    credit: 280,
    balanceAfter: 560,
    recordedBy: 'سامح عبد الله (المدير)',
    authorizedBy: 'سامح عبد الله (المدير)',
  },
  {
    id: 'led-9',
    employeeId: 'emp-3',
    date: '2026-08-19',
    time: '02:00',
    type: 'withdrawal',
    description: 'سحب من رصيده المستحق نقداً',
    debit: 300,
    credit: 0,
    balanceAfter: 260,
    recordedBy: 'سامح عبد الله (المدير)',
  },

  // إبراهيم سيد:
  {
    id: 'led-10',
    employeeId: 'emp-5',
    date: '2026-08-19',
    time: '08:00',
    type: 'daily_wage',
    description: 'تسجيل يومية عمل',
    debit: 0,
    credit: 220,
    balanceAfter: 220,
    recordedBy: 'سامح عبد الله (المدير)',
  },
];

export const INITIAL_SHIFTS: Shift[] = [
  // Past closed shift (Yesterday Night Shift)
  {
    id: 'shift-1001',
    shiftName: 'وردية ليلية',
    openedByUserId: 'u-cashier-ahmed',
    openedByUserName: 'أحمد صبحي (كاشير)',
    openedAt: '2026-08-18 20:00',
    openingCash: 1500,
    status: 'closed',
    closedByUserId: 'u-cashier-ahmed',
    closedByUserName: 'أحمد صبحي (كاشير)',
    closedAt: '2026-08-19 08:00',
    expectedCash: 12450,
    actualCash: 12300,
    cashDifference: -150, // عجز 150 ج
    differenceReason: 'عجز ناتج عن خطأ في باقي طلب دليفري تم تدقيقه',
    differenceAuthorizedBy: 'سامح عبد الله (المدير)',
    totalSales: 14200,
    cashSales: 11950,
    cardSales: 2250,
    instapaySales: 0,
    totalExpenses: 800,
    totalCashIn: 0,
    totalCashOut: 200,
    totalRefunds: 0,
    totalDiscounts: 0,
    ordersCount: 38,
    notes: 'تم تقفيل الوردية بعد تسليم الخزنة وتدقيق العجز مع المدير',
  },
  // Most recent closed shift. The prototype intentionally starts without an
  // active shift so selling and drawer operations require an explicit opening.
  {
    id: 'shift-1002',
    shiftName: 'وردية صباحية',
    openedByUserId: 'u-cashier-ahmed',
    openedByUserName: 'أحمد صبحي (كاشير)',
    openedAt: '2026-08-19 08:00',
    openingCash: 2000,
    status: 'closed',
    closedByUserId: 'u-cashier-ahmed',
    closedByUserName: 'أحمد صبحي (كاشير)',
    closedAt: '2026-08-19 16:00',
    expectedCash: 4600,
    actualCash: 4600,
    cashDifference: 0,
    totalSales: 3450,
    cashSales: 2950,
    cardSales: 500,
    instapaySales: 0,
    totalExpenses: 350,
    totalCashIn: 0,
    totalCashOut: 0,
    totalRefunds: 0,
    totalDiscounts: 0,
    ordersCount: 12,
    notes: 'تم تقفيل الوردية دون فروق',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-124',
    orderNumber: '#0124',
    sequenceNumber: 124,
    createdAt: '2026-08-19 08:25',
    cashierId: 'u-cashier-ahmed',
    cashierName: 'أحمد صبحي',
    shiftId: 'shift-1002',
    orderType: 'dine_in',
    tableNumber: 'صالة 4',
    items: [
      {
        id: 'item-1',
        productId: 'p-half-chicken',
        productName: 'نص فرخة مشوية ع الفحم',
        unitPrice: 165,
        quantity: 1,
        totalPrice: 165,
        sendToGrill: true,
        notes: 'مستوية كويس + سلطة زيادة',
      },
      {
        id: 'item-2',
        productId: 'p-rice',
        productName: 'طبق أرز فالح المبهر',
        variantId: 'v-med',
        variantName: 'وسط',
        unitPrice: 50,
        quantity: 2,
        totalPrice: 100,
        sendToGrill: false,
      },
      {
        id: 'item-3',
        productId: 'p-bev-can',
        productName: 'كانز (بيبسي)',
        variantId: 'v-pepsi',
        variantName: 'بيبسي',
        unitPrice: 20,
        quantity: 2,
        totalPrice: 40,
        sendToGrill: false,
      },
    ],
    subtotal: 305,
    discount: 0,
    total: 305,
    paymentMethod: 'cash',
    amountPaid: 350,
    changeDue: 45,
    status: 'completed',
    isPaid: true,
    paidAt: '2026-08-19 08:26',
    hasGrillItems: true,
    grillStatus: 'ready',
  },
  {
    id: 'ord-125',
    orderNumber: '#0125',
    sequenceNumber: 125,
    createdAt: '2026-08-19 08:45',
    cashierId: 'u-cashier-ahmed',
    cashierName: 'أحمد صبحي',
    shiftId: 'shift-1002',
    orderType: 'takeaway',
    items: [
      {
        id: 'item-4',
        productId: 'p-kofta-sandwich',
        productName: 'ساندوتش كفتة ع الفحم',
        variantId: 'v-saj',
        variantName: 'صاج',
        unitPrice: 90,
        quantity: 3,
        totalPrice: 270,
        sendToGrill: true,
        notes: 'طحينة زيادة وبدون شطة',
      },
      {
        id: 'item-5',
        productId: 'p-plate-fries',
        productName: 'طبق بطاطس',
        variantId: 'v-med',
        variantName: 'وسط',
        unitPrice: 30,
        quantity: 1,
        totalPrice: 30,
        sendToGrill: false,
      },
      {
        id: 'item-6',
        productId: 'p-bev-can',
        productName: 'كانز (سفن آب)',
        variantId: 'v-7up',
        variantName: 'سفن آب',
        unitPrice: 20,
        quantity: 2,
        totalPrice: 40,
        sendToGrill: false,
      },
    ],
    subtotal: 340,
    discount: 0,
    total: 340,
    paymentMethod: 'card',
    amountPaid: 340,
    changeDue: 0,
    status: 'preparing',
    isPaid: true,
    paidAt: '2026-08-19 08:46',
    hasGrillItems: true,
    grillStatus: 'preparing',
  },
  {
    id: 'ord-126',
    orderNumber: '#0126',
    sequenceNumber: 126,
    createdAt: '2026-08-19 09:10',
    cashierId: 'u-cashier-ahmed',
    cashierName: 'أحمد صبحي',
    shiftId: 'shift-1002',
    orderType: 'delivery',
    customerName: 'الأستاذ طارق ممدوح',
    customerPhone: '01022334455',
    deliveryAddress: 'عمارة 14 - المجاورة الثالثة - الحي السابع',
    deliveryFee: 20,
    items: [
      {
        id: 'item-7',
        productId: 'p-meal-shish-kofta',
        productName: 'وجبة شيش + كفتة',
        unitPrice: 170,
        quantity: 2,
        totalPrice: 340,
        sendToGrill: true,
        notes: 'سلطة خضرا وتومية زيادة',
      },
      {
        id: 'item-8',
        productId: 'p-pasta-bechamel',
        productName: 'مكرونة بشاميل',
        unitPrice: 50,
        quantity: 1,
        totalPrice: 50,
        sendToGrill: false,
      },
      {
        id: 'item-9',
        productId: 'p-bev-liter',
        productName: 'مشروب غازي 1 لتر',
        variantId: 'v-1l-pepsi',
        variantName: 'بيبسي 1 لتر',
        unitPrice: 35,
        quantity: 1,
        totalPrice: 35,
        sendToGrill: false,
      },
    ],
    subtotal: 445,
    discount: 0,
    total: 445,
    paymentMethod: 'cash',
    amountPaid: 500,
    changeDue: 55,
    status: 'pending',
    isPaid: true,
    paidAt: '2026-08-19 09:11',
    hasGrillItems: true,
    grillStatus: 'pending',
  },
  {
    id: 'ord-127',
    orderNumber: '#0127',
    sequenceNumber: 127,
    createdAt: '2026-08-19 09:30',
    cashierId: 'u-cashier-ahmed',
    cashierName: 'أحمد صبحي',
    shiftId: 'shift-1002',
    orderType: 'dine_in',
    tableNumber: 'صالة 2',
    items: [
      {
        id: 'item-10',
        productId: 'p-quarter-kg-kofta',
        productName: 'ربع كيلو كفتة مشوية',
        unitPrice: 150,
        quantity: 1,
        totalPrice: 150,
        sendToGrill: true,
      },
      {
        id: 'item-11',
        productId: 'p-shish-sandwich',
        productName: 'ساندوتش شيش طاووق',
        variantId: 'v-french',
        variantName: 'فرنساوي',
        unitPrice: 100,
        quantity: 1,
        totalPrice: 100,
        sendToGrill: true,
      },
      {
        id: 'item-12',
        productId: 'p-app-toum',
        productName: 'تومية سورية',
        variantId: 'v-large',
        variantName: 'كبير',
        unitPrice: 30,
        quantity: 1,
        totalPrice: 30,
        sendToGrill: false,
      },
    ],
    subtotal: 280,
    discount: 0,
    total: 280,
    paymentMethod: 'cash',
    amountPaid: 300,
    changeDue: 20,
    status: 'pending',
    isPaid: true,
    paidAt: '2026-08-19 09:31',
    hasGrillItems: true,
    grillStatus: 'pending',
  },
];

export const INITIAL_GRILL_TICKETS: GrillTicket[] = [
  {
    id: 'gt-125',
    orderId: 'ord-125',
    orderNumber: '#0125',
    createdAt: '2026-08-19 08:45',
    orderType: 'takeaway',
    items: [
      {
        productId: 'p-kofta-sandwich',
        productName: 'ساندوتش كفتة ع الفحم',
        variantName: 'صاج',
        quantity: 3,
        notes: 'طحينة زيادة وبدون شطة',
      },
    ],
    status: 'preparing',
    startedAt: '2026-08-19 08:48',
  },
  {
    id: 'gt-126',
    orderId: 'ord-126',
    orderNumber: '#0126',
    createdAt: '2026-08-19 09:10',
    orderType: 'delivery',
    items: [
      {
        productId: 'p-meal-shish-kofta',
        productName: 'وجبة شيش + كفتة',
        quantity: 2,
        notes: 'سلطة خضرا وتومية زيادة',
      },
    ],
    status: 'pending',
  },
  {
    id: 'gt-127',
    orderId: 'ord-127',
    orderNumber: '#0127',
    createdAt: '2026-08-19 09:30',
    orderType: 'dine_in',
    items: [
      {
        productId: 'p-quarter-kg-kofta',
        productName: 'ربع كيلو كفتة مشوية',
        quantity: 1,
      },
      {
        productId: 'p-shish-sandwich',
        productName: 'ساندوتش شيش طاووق',
        variantName: 'فرنساوي',
        quantity: 1,
      },
    ],
    status: 'pending',
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-1',
    date: '2026-08-19',
    time: '08:30',
    category: 'شراء مستلزمات',
    amount: 150,
    description: 'شراء خضار طازج (بقدونس، خيار، طماطم) من السوق',
    userId: 'u-cashier-ahmed',
    userName: 'أحمد صبحي',
    shiftId: 'shift-1002',
    paidFromDrawer: true,
    receiptNumber: 'REC-901',
  },
  {
    id: 'exp-2',
    date: '2026-08-19',
    time: '09:00',
    category: 'غاز',
    amount: 200,
    description: 'تبديل أسطوانة غاز لمطبخ السندوتشات',
    userId: 'u-cashier-ahmed',
    userName: 'أحمد صبحي',
    shiftId: 'shift-1002',
    paidFromDrawer: true,
    receiptNumber: 'GAS-441',
  },
];

export const INITIAL_CASH_MOVEMENTS: CashMovement[] = [
  {
    id: 'cm-1',
    date: '2026-08-19',
    time: '08:00',
    type: 'cash_in',
    amount: 2000,
    reason: 'رصيد افتتاح درج الكاشير للوردية الصباحية',
    userId: 'u-cashier-ahmed',
    userName: 'أحمد صبحي',
    shiftId: 'shift-1002',
  },
  {
    id: 'cm-2',
    date: '2026-08-19',
    time: '08:15',
    type: 'drawer_open',
    amount: 0,
    reason: 'فتح الدرج لتبديل فكة مع الصراف',
    userId: 'u-cashier-ahmed',
    userName: 'أحمد صبحي',
    shiftId: 'shift-1002',
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-1',
    employeeId: 'emp-1',
    employeeName: 'أحمد صبحي محمود',
    date: '2026-08-19',
    checkIn: '07:55',
    shiftName: 'وردية صباحية',
    status: 'present',
    lateMinutes: 0,
    workHours: 8,
    overtimeHours: 0,
    tatbiqCount: 0,
    isManualCorrection: false,
  },
  {
    id: 'att-2',
    employeeId: 'emp-2',
    employeeName: 'محمد علي حسن',
    date: '2026-08-19',
    checkIn: '08:20',
    shiftName: 'وردية صباحية',
    status: 'late',
    lateMinutes: 20,
    workHours: 7.6,
    overtimeHours: 0,
    tatbiqCount: 0,
    isManualCorrection: false,
  },
  {
    id: 'att-3',
    employeeId: 'emp-3',
    employeeName: 'محمود الشامي',
    date: '2026-08-19',
    checkIn: '07:50',
    shiftName: 'وردية صباحية',
    status: 'present',
    lateMinutes: 0,
    workHours: 8,
    overtimeHours: 0,
    tatbiqCount: 0,
    isManualCorrection: false,
  },
  {
    id: 'att-4',
    employeeId: 'emp-4',
    employeeName: 'سامح عبد الله',
    date: '2026-08-19',
    checkIn: '08:00',
    shiftName: 'وردية صباحية',
    status: 'present',
    lateMinutes: 0,
    workHours: 8,
    overtimeHours: 0,
    tatbiqCount: 0,
    isManualCorrection: false,
  },
  {
    id: 'att-5',
    employeeId: 'emp-5',
    employeeName: 'إبراهيم سيد عواد',
    date: '2026-08-19',
    checkIn: '07:58',
    shiftName: 'وردية صباحية',
    status: 'present',
    lateMinutes: 0,
    workHours: 8,
    overtimeHours: 0,
    tatbiqCount: 0,
    isManualCorrection: false,
  },
  {
    id: 'att-6',
    employeeId: 'emp-6',
    employeeName: 'كريم مجدي فتحي',
    date: '2026-08-19',
    shiftName: 'وردية صباحية',
    status: 'absent',
    lateMinutes: 0,
    workHours: 0,
    overtimeHours: 0,
    tatbiqCount: 0,
    isManualCorrection: false,
  },
];

export const INITIAL_AUDIT_EVENTS: AuditEvent[] = [
  {
    id: 'aud-1',
    timestamp: '2026-08-19 08:00:15',
    userId: 'u-cashier-ahmed',
    userName: 'أحمد صبحي',
    userRole: 'cashier',
    action: 'افتتاح وردية جديدة',
    category: 'shift',
    details: 'تم فتح الوردية الصباحية برصيد افتتاح درج 2000 ج.م',
    severity: 'normal',
    shiftId: 'shift-1002',
    device: 'كاشير رئيسي - POS 1',
  },
  {
    id: 'aud-2',
    timestamp: '2026-08-19 08:15:30',
    userId: 'u-cashier-ahmed',
    userName: 'أحمد صبحي',
    userRole: 'cashier',
    action: 'فتح درج النقدية بدون عملية بيع',
    category: 'cash',
    details: 'تم فتح الدرج يدوياً لتبديل فكة 200 ج مع الصراف',
    severity: 'warning',
    shiftId: 'shift-1002',
    device: 'كاشير رئيسي - POS 1',
    reason: 'تبديل فكة',
  },
  {
    id: 'aud-3',
    timestamp: '2026-08-19 08:26:00',
    userId: 'u-cashier-ahmed',
    userName: 'أحمد صبحي',
    userRole: 'cashier',
    action: 'إنشاء ودفع طلب #0124',
    category: 'order',
    details: 'طلب صالة بقيمة 305 ج.م - مدفوع كاش - تم إرسال أصناف الفحم لشاشة التحضير',
    severity: 'normal',
    shiftId: 'shift-1002',
    device: 'كاشير رئيسي - POS 1',
  },
  {
    id: 'aud-4',
    timestamp: '2026-08-19 08:30:10',
    userId: 'u-cashier-ahmed',
    userName: 'أحمد صبحي',
    userRole: 'cashier',
    action: 'تسجيل مصروف من الدرج',
    category: 'cash',
    details: 'مصروف شراء مستلزمات خضار بقيمة 150 ج.م',
    severity: 'normal',
    shiftId: 'shift-1002',
    device: 'كاشير رئيسي - POS 1',
  },
  {
    id: 'aud-5',
    timestamp: '2026-08-19 08:46:12',
    userId: 'u-cashier-ahmed',
    userName: 'أحمد صبحي',
    userRole: 'cashier',
    action: 'إنشاء ودفع طلب #0125',
    category: 'order',
    details: 'طلب تيك أواي بقيمة 340 ج.م - مدفوع بطاقة بنكية',
    severity: 'normal',
    shiftId: 'shift-1002',
    device: 'كاشير رئيسي - POS 1',
  },
  {
    id: 'aud-6',
    timestamp: '2026-08-18 20:00:00',
    userId: 'u-manager',
    userName: 'سامح عبد الله',
    userRole: 'manager',
    action: 'تسجيل سلفة موظف',
    category: 'employee',
    details: 'تسجيل سلفة 500 ج.م للموظف محمد علي حسن — تحول رصيده إلى سالب (-200 ج.م)',
    severity: 'warning',
    reason: 'سلفة شراء مستلزمات عائلية',
    authorizedBy: 'الحاج فالح (المالك)',
  },
  {
    id: 'aud-7',
    timestamp: '2026-08-19 08:02:10',
    userId: 'u-cashier-ahmed',
    userName: 'أحمد صبحي',
    userRole: 'cashier',
    action: 'تقفيل وردية سابقة مع وجود عجز نقدية',
    category: 'shift',
    details: 'تقفيل وردية ليلية: المتوقع 12,450 ج.م، الفعلي المدخل 12,300 ج.م، عجز: -150 ج.م',
    severity: 'critical',
    shiftId: 'shift-1001',
    reason: 'عجز ناتج عن خطأ في باقي طلب دليفري',
    authorizedBy: 'سامح عبد الله (المدير)',
  },
];

export const INITIAL_DEVICES: Device[] = [
  {
    id: 'dev-1',
    name: 'شاشة الكاشير الرئيسية (Windows POS 1)',
    type: 'pos',
    ipAddress: '192.168.1.101',
    status: 'connected',
    lastSeen: 'الآن (متصل)',
    details: 'Windows 11 POS Edition - معالج Core i5 / شاشة لمس 1920x1080',
  },
  {
    id: 'dev-2',
    name: 'طابعة الإيصالات الحرارية (80mm Thermal Receipt)',
    type: 'printer',
    ipAddress: '192.168.1.200 (USB/LAN)',
    status: 'connected',
    lastSeen: 'الآن (متصلة وجاهزة للطباعة)',
    details: 'Xprinter XP-N160II - عرض 80mm - قص تلقائي',
  },
  {
    id: 'dev-3',
    name: 'شاشة محطة الفحم التاتش (Grill Station KDS)',
    type: 'grill',
    ipAddress: '192.168.1.105',
    status: 'connected',
    lastSeen: 'الآن (متصلة وتستقبل الطلبات)',
    details: 'شاشة لمس صناعية 21 بوصة - كشك الشواية والتحضير',
  },
  {
    id: 'dev-4',
    name: 'جهاز بصمة حضور الموظفين (Biometric Fingerprint)',
    type: 'fingerprint',
    ipAddress: '192.168.1.220',
    status: 'connected',
    lastSeen: 'الآن (متصل - مزامنة لحظية)',
    details: 'ZKTeco K40 Biometric Attendance Device',
  },
  {
    id: 'dev-5',
    name: 'خادم قاعدة البيانات المحلي (Local Restaurant Server)',
    type: 'server',
    ipAddress: '127.0.0.1 (Localhost)',
    status: 'connected',
    lastSeen: 'الآن (يعمل محلياً بدون إنترنت)',
    details: 'Windows Service Host - يعمل 24 ساعة دون الحاجة لسحابة خارجية',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'تنبيه عجز في الوردية السابقة',
    message: 'تم تسجيل عجز بقيمة 150 ج.م في الوردية الليلية السابقة بواسطة أحمد صبحي',
    severity: 'danger',
    timestamp: 'منذ ساعتين',
    read: false,
    linkModule: 'control_center',
  },
  {
    id: 'notif-2',
    title: 'سلفة موظف مرتفعة',
    message: 'الموظف محمد علي حسن رصيده سالب بمقدار -200 ج.م بعد سلفة 500 ج.م',
    severity: 'warning',
    timestamp: 'منذ 4 ساعات',
    read: false,
    linkModule: 'employees',
  },
  {
    id: 'notif-3',
    title: 'جاهزية طابعة الإيصالات',
    message: 'تم اختبار طابعة الإيصالات 80mm وهي جاهزة للعمل بكفاءة',
    severity: 'info',
    timestamp: 'منذ 5 ساعات',
    read: true,
    linkModule: 'devices',
  },
];
