const creditTypes=new Set(['daily_wage','salary','overtime','extra_shift','bonus','other_earning']);
export const PAYROLL_TRANSITIONS={draft:['calculated','cancelled'],calculated:['reviewed','cancelled'],reviewed:['approved','cancelled'],approved:['paid','cancelled'],paid:[],cancelled:[]};
export function employeeLedgerBalance(entries,employeeId){return entries.filter(x=>x.employeeId===employeeId).reduce((s,x)=>s+(Number(x.credit)||0)-(Number(x.debit)||0),0)}
export function assertUniqueDailyWage(entries,{employeeId,date,shiftId}){if(entries.some(x=>x.employeeId===employeeId&&x.type==='daily_wage'&&x.date===date&&(x.shiftId||'normal')===(shiftId||'normal')))throw new Error('تم تسجيل اليومية العادية لهذا الموظف في نفس اليوم والوردية بالفعل. استخدم تطبيق لوردية إضافية.');}
export function buildEarningEntry({id,employeeId,type,date,time='00:00',amount,createdBy,shiftId,referenceId,hours,rateSnapshot,valueSnapshot}){if(!creditTypes.has(type)||!Number.isFinite(amount)||amount<=0)throw new Error('حركة الاستحقاق غير صالحة.');return{id,employeeId,date,time,type,description:type,credit:amount,debit:0,balanceAfter:0,recordedBy:createdBy,shiftId,referenceId,hours,rateSnapshot,valueSnapshot};}
export function outstandingAdvance(entries,employeeId){return Math.max(0,entries.filter(x=>x.employeeId===employeeId).reduce((s,x)=>s+(x.type==='advance'?x.debit:0)-(x.type==='payroll_settlement'?(x.advanceDeduction||0):0),0))}
export function calculatePayrollLines({period,employees,entries,advanceDeductions={}}){if(!/^\d{4}-\d{2}$/.test(period))throw new Error('فترة Payroll غير صالحة.');return employees.flatMap(emp=>{const pe=entries.filter(x=>x.employeeId===emp.id&&String(x.date).slice(0,7)===period);const has=pe.some(x=>creditTypes.has(x.type));if(!emp.isActive&&!has)return[];const base=emp.compensationType==='monthly'?(emp.monthlySalary||0):pe.filter(x=>x.type==='daily_wage'||x.type==='salary').reduce((s,x)=>s+x.credit,0);const overtime=pe.filter(x=>x.type==='overtime').reduce((s,x)=>s+x.credit,0);const extraShifts=pe.filter(x=>x.type==='extra_shift').reduce((s,x)=>s+x.credit,0);const bonuses=pe.filter(x=>x.type==='bonus'||x.type==='other_earning').reduce((s,x)=>s+x.credit,0);const deductions=pe.filter(x=>x.type==='deduction'||x.type==='adjustment').reduce((s,x)=>s+x.debit,0);const requested=advanceDeductions[emp.id]||0;const available=outstandingAdvance(entries,emp.id);if(requested<0||requested>available)throw new Error(`استقطاع السلفة للموظف ${emp.name} يتجاوز الرصيد المتفق عليه.`);return[{employeeId:emp.id,base,overtime,extraShifts,bonuses,deductions,advanceDeductions:requested,netPayable:Math.max(0,base+overtime+extraShifts+bonuses-deductions-requested),status:'unpaid'}]})}
export function assertPayrollTransition(from,to){if(!PAYROLL_TRANSITIONS[from]?.includes(to))throw new Error(`انتقال حالة Payroll غير مسموح: ${from} → ${to}`)}
export function payrollReport(lines){return lines.reduce((r,x)=>{const earned=x.base+x.overtime+x.extraShifts+x.bonuses;const paid=x.status==='paid'?x.netPayable:0;return{earned:r.earned+earned,paid:r.paid+paid,outstanding:r.outstanding+(x.status==='paid'?0:x.netPayable)}},{earned:0,paid:0,outstanding:0})}
export function buildPayrollSettlements({run,lines,operationId,movementId,paidBy,timestamp=new Date().toISOString()}){return lines.filter(x=>x.netPayable>0).map(x=>({id:`payroll-settlement-${run.id}-${x.id}`,employeeId:x.employeeId,date:timestamp.slice(0,10),time:timestamp.slice(11,16),type:'payroll_settlement',description:`تسوية Payroll ${run.period}`,debit:x.netPayable/100,credit:0,balanceAfter:0,recordedBy:paidBy,referenceId:run.id,payrollRunId:run.id,payrollLineId:x.id,amountPiastres:x.netPayable,advanceDeduction:x.advanceDeductions/100,operationId,treasuryMovementId:movementId,paidBy}))}
