'use client';
import React, { useState } from 'react';
import { useEnterpriseStore } from '@/lib/enterprise-store';
import { useAppStore } from '@/lib/store';
import { Building2, PackageCheck, Plus, ReceiptText } from 'lucide-react';
const money=(p:number)=>`${(p/100).toLocaleString('ar-EG',{minimumFractionDigits:2})} ج`;

export default function PurchasingScreen(){
 const s=useEnterpriseStore(),app=useAppStore(); const [tab,setTab]=useState<'suppliers'|'purchase'>('suppliers');
 const [supplierName,setSupplierName]=useState(''),[phone,setPhone]=useState(''),[supplierId,setSupplierId]=useState('');
 const [itemId,setItemId]=useState(s.inventoryItems[0]?.id||''),[quantity,setQuantity]=useState(''),[unitCost,setUnitCost]=useState(''),[paid,setPaid]=useState(''),[invoice,setInvoice]=useState(''),[error,setError]=useState('');
 const [method,setMethod]=useState<'cash'|'instapay'|'bank'|'credit'>('credit'); const [payPurchaseId,setPayPurchaseId]=useState(''),[laterAmount,setLaterAmount]=useState(''),[laterMethod,setLaterMethod]=useState<'cash'|'instapay'|'bank'>('cash');
 const addSupplier=()=>{if(!supplierName.trim())return;s.addSupplier({name:supplierName.trim(),phone,address:'',category:'مورد خامات',active:true,notes:''});setSupplierName('');setPhone('');};
 const receive=()=>{const qty=Math.round(Number(quantity)*1000),cost=Math.round(Number(unitCost)*100),paidP=Math.round(Number(paid||0)*100);if(!supplierId||!itemId||qty<=0||cost<=0)return;try{const purchase=s.receivePurchase({requestId:crypto.randomUUID(),supplierId,invoiceNumber:invoice.trim()||undefined,lines:[{id:crypto.randomUUID(),inventoryItemId:itemId,quantityMilliUnits:qty,unitCost:cost}],paid:paidP,paymentMethod:method,receivedBy:app.currentUser.name,createdBy:app.currentUser.name});app.logAuditEvent({userId:app.currentUser.id,userName:app.currentUser.name,userRole:app.currentUser.role,action:`استلام فاتورة مشتريات ${purchase.invoiceNumber||purchase.id}`,category:'inventory',details:`الإجمالي ${money(purchase.total)} - المدفوع ${money(purchase.paid)} - المصدر ${purchase.paymentAccountId||'آجل'}`,severity:'normal',operationId:purchase.operationId,referenceId:purchase.id});setQuantity('');setUnitCost('');setPaid('');setInvoice('');setError('');}catch(cause){setError(cause instanceof Error?cause.message:'تعذر استلام الفاتورة.');}};
 const payLater=()=>{const value=Math.round(Number(laterAmount)*100);if(!payPurchaseId||value<=0)return;try{const purchase=s.payPurchase({requestId:crypto.randomUUID(),purchaseId:payPurchaseId,amount:value,paymentMethod:laterMethod,createdBy:app.currentUser.name,approvedBy:app.currentUser.name});app.logAuditEvent({userId:app.currentUser.id,userName:app.currentUser.name,userRole:app.currentUser.role,action:`سداد مورد للفاتورة ${purchase.invoiceNumber||purchase.id}`,category:'cash',details:`المبلغ ${money(value)} - المصدر ${laterMethod}`,severity:'normal',referenceId:purchase.id,authorizedBy:app.currentUser.name});setLaterAmount('');setError('');}catch(cause){setError(cause instanceof Error?cause.message:'تعذر تسجيل السداد.');}};
 const unpaid=s.purchases.filter(p=>p.status!=='cancelled'&&(p.remainingAmount??p.total-p.paid)>0);
 return <div className="space-y-5 bg-slate-100 p-6" dir="rtl"><div className="flex items-center justify-between rounded-3xl border bg-white p-5"><div className="flex items-center gap-3"><div className="rounded-2xl bg-amber-50 p-3 text-amber-700"><PackageCheck/></div><div><h1 className="text-xl font-black">الموردون والمشتريات</h1><p className="text-xs text-slate-500">الفاتورة والدفع واستلام المخزون مترابطون بمرجع واحد</p></div></div><div className="flex rounded-xl bg-slate-100 p-1 text-xs font-bold"><button onClick={()=>setTab('suppliers')} className={`rounded-lg px-4 py-2 ${tab==='suppliers'?'bg-white shadow':''}`}>الموردون</button><button onClick={()=>setTab('purchase')} className={`rounded-lg px-4 py-2 ${tab==='purchase'?'bg-white shadow':''}`}>استلام مشتريات</button></div></div>
 {error&&<p className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}
 {tab==='suppliers'?<div className="grid gap-4 lg:grid-cols-[360px_1fr]"><div className="space-y-3 rounded-3xl border bg-white p-5"><h2 className="flex items-center gap-2 font-black"><Building2 className="h-4 w-4"/>إضافة مورد</h2><input value={supplierName} onChange={e=>setSupplierName(e.target.value)} placeholder="اسم المورد" className="w-full rounded-xl border p-3"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="رقم الهاتف" className="w-full rounded-xl border p-3"/><button onClick={addSupplier} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#0F52BA] p-3 text-sm font-black text-white"><Plus className="h-4 w-4"/>حفظ المورد</button></div><div className="overflow-hidden rounded-3xl border bg-white"><div className="grid grid-cols-5 bg-slate-50 p-4 text-xs font-black"><span>المورد</span><span>الهاتف</span><span>المشتريات</span><span>المدفوعات</span><span>المستحق</span></div>{s.suppliers.map(x=><div key={x.id} className="grid grid-cols-5 border-t p-4 text-xs"><b>{x.name}</b><span>{x.phone||'-'}</span><span>{money(s.supplierLedger.filter(e=>e.supplierId===x.id&&e.type==='purchase_invoice').reduce((n,e)=>n+e.debit,0))}</span><span>{money(s.supplierLedger.filter(e=>e.supplierId===x.id&&(e.type==='supplier_payment'||e.type==='payment')).reduce((n,e)=>n+e.credit,0))}</span><b className={s.supplierBalance(x.id)>0?'text-red-700':'text-emerald-700'}>{money(s.supplierBalance(x.id))}</b></div>)}</div></div>
 :<div className="grid gap-4 lg:grid-cols-[400px_1fr]"><div className="space-y-4"><div className="space-y-3 rounded-3xl border bg-white p-5"><h2 className="flex items-center gap-2 font-black"><ReceiptText className="h-4 w-4"/>استلام فاتورة</h2><select value={supplierId} onChange={e=>setSupplierId(e.target.value)} className="w-full rounded-xl border p-3"><option value="">اختر المورد</option>{s.suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input value={invoice} onChange={e=>setInvoice(e.target.value)} placeholder="رقم/مرجع الفاتورة" className="w-full rounded-xl border p-3"/><select value={itemId} onChange={e=>setItemId(e.target.value)} className="w-full rounded-xl border p-3">{s.inventoryItems.map(x=><option key={x.id} value={x.id}>{x.name} — {x.unit}</option>)}</select><div className="grid grid-cols-2 gap-2"><input type="number" value={quantity} onChange={e=>setQuantity(e.target.value)} placeholder="الكمية" className="rounded-xl border p-3"/><input type="number" value={unitCost} onChange={e=>setUnitCost(e.target.value)} placeholder="تكلفة الوحدة" className="rounded-xl border p-3"/></div><div className="grid grid-cols-2 gap-2"><input type="number" value={paid} onChange={e=>setPaid(e.target.value)} placeholder="المدفوع الآن" className="rounded-xl border p-3"/><select value={method} onChange={e=>setMethod(e.target.value as typeof method)} className="rounded-xl border p-3"><option value="credit">آجل</option><option value="cash">الخزينة الرئيسية</option><option value="instapay">InstaPay</option><option value="bank">بنك</option></select></div><button onClick={receive} className="flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-600 p-3 text-sm font-black text-white"><PackageCheck className="h-4 w-4"/>اعتماد الاستلام</button></div>
 <div className="space-y-3 rounded-3xl border bg-white p-5"><h2 className="font-black">سداد لاحق لفاتورة محددة</h2><select value={payPurchaseId} onChange={e=>setPayPurchaseId(e.target.value)} className="w-full rounded-xl border p-3"><option value="">اختر الفاتورة</option>{unpaid.map(p=><option key={p.id} value={p.id}>{p.invoiceNumber||p.id} — متبقي {money(p.remainingAmount??p.total-p.paid)}</option>)}</select><div className="grid grid-cols-2 gap-2"><input type="number" value={laterAmount} onChange={e=>setLaterAmount(e.target.value)} placeholder="مبلغ السداد" className="rounded-xl border p-3"/><select value={laterMethod} onChange={e=>setLaterMethod(e.target.value as typeof laterMethod)} className="rounded-xl border p-3"><option value="cash">الخزينة الرئيسية</option><option value="bank">البنك</option><option value="instapay">InstaPay</option></select></div><button onClick={payLater} className="w-full rounded-xl bg-[#0F52BA] p-3 text-sm font-black text-white">تسجيل سداد المورد</button></div></div>
 <div className="overflow-hidden rounded-3xl border bg-white"><div className="grid grid-cols-6 bg-slate-50 p-4 text-xs font-black"><span>التاريخ</span><span>المرجع</span><span>المورد</span><span>الإجمالي</span><span>المدفوع</span><span>المتبقي</span></div>{s.purchases.map(p=><div key={p.id} className="grid grid-cols-6 border-t p-4 text-xs"><span>{new Date(p.createdAt).toLocaleDateString('ar-EG')}</span><span>{p.invoiceNumber||'-'}</span><b>{s.suppliers.find(x=>x.id===p.supplierId)?.name}</b><span>{money(p.total)}</span><span>{money(p.paid)}</span><b>{money(p.remainingAmount??p.total-p.paid)}</b></div>)}</div></div>}
 </div>;
}
