'use client';
import React,{useMemo,useState} from 'react';
import {useAppStore} from '@/lib/store'; import {useEnterpriseStore} from '@/lib/enterprise-store';
import {calculateDenominationCount,EGYPTIAN_DENOMINATIONS_PIASTRES,evaluateCloseBlockers,reconcileBusinessDay,selectBusinessDayRecords} from '@/lib/control-layer-domain.mjs';
import {readFinancialJournal} from '@/lib/financial-journal.mjs'; import {CalendarCheck,Printer,ShieldAlert} from 'lucide-react';
import {usePersistenceIssue} from '@/lib/persistence-health';
const money=(p:number)=>(p/100).toLocaleString('ar-EG',{minimumFractionDigits:2})+' ج';
export default function DailySettlementScreen(){
 const app=useAppStore(),enterprise=useEnterpriseStore(),persistenceIssue=usePersistenceIssue(),activeDay=enterprise.businessDays.find(x=>x.status!=='closed'),day=activeDay||enterprise.businessDays[0];
 const [qty,setQty]=useState<Record<number,number>>({}),[drop,setDrop]=useState(''),[message,setMessage]=useState(''),[businessDate,setBusinessDate]=useState(new Date().toISOString().slice(0,10));
 const shifts=useMemo(()=>selectBusinessDayRecords(app.shifts,day,app.shifts),[app.shifts,day]);
 const rec=useMemo(()=>reconcileBusinessDay({day,orders:app.orders,shifts:app.shifts,expenses:app.expenses,treasuryMovements:enterprise.treasuryMovements,driverCustodies:enterprise.driverCustodies,driverSettlements:enterprise.driverSettlements,purchases:enterprise.purchases,payrollRuns:enterprise.payrollRuns}),[day,app.orders,app.shifts,app.expenses,enterprise.treasuryMovements,enterprise.driverCustodies,enterprise.driverSettlements,enterprise.purchases,enterprise.payrollRuns]);
 const count=calculateDenominationCount(EGYPTIAN_DENOMINATIONS_PIASTRES.map(denominationPiastres=>({denominationPiastres,quantity:qty[denominationPiastres]||0})),rec.shifts.actualPiastres);
 const items=enterprise.checklistItems.filter(x=>x.active).sort((a,b)=>a.phase.localeCompare(b.phase)||a.sortOrder-b.sortOrder),done=(id:string)=>enterprise.checklistCompletions.some(x=>x.businessDayId===day.id&&x.itemId===id&&x.completed);
 const journal=()=>readFinancialJournal(localStorage),blockers=evaluateCloseBlockers({shifts,deliveryTrips:enterprise.deliveryTrips,driverCustodies:enterprise.driverCustodies,journalEntries:typeof window==='undefined'?[]:journal(),persistenceHealthy:!persistenceIssue,requiredChecklist:day?items.filter(x=>x.phase==='closing'&&x.required).map(x=>({...x,completed:done(x.id)})):[],reconciliation:rec});
 const attempt=(fn:()=>void,ok:string)=>{try{fn();setMessage(ok)}catch(e){setMessage(e instanceof Error?e.message:'تعذر التنفيذ.')}};
 const cards=[['إجمالي المبيعات',rec.sales.grossSalesPiastres],['المرتجعات',-rec.sales.refundsPiastres],['صافي المبيعات',rec.sales.netSalesPiastres],['المصروفات',-rec.expenses.totalPiastres],['عهد السائقين',rec.delivery.expectedPiastres],['فرق المطابقة',rec.differencePiastres]] as const;
 return <div className="space-y-5 bg-slate-100 p-6" dir="rtl"><header className="flex items-center justify-between rounded-3xl border bg-white p-5"><div><CalendarCheck className="inline"/> <b className="text-xl">رقابة وإغلاق يوم العمل</b><p className="text-xs text-slate-500">{day?`تاريخ العمل ${day.businessDate||day.date} — الحالة ${day.status} — مرات الإغلاق ${day.closeRevision||0}`:'لا يوجد يوم تشغيلي'}</p></div><div className="flex gap-2">{!activeDay&&<><input type="date" value={businessDate} onChange={e=>setBusinessDate(e.target.value)} className="rounded-xl border p-2"/><button data-testid="open-business-day" className="rounded-xl bg-emerald-700 px-3 text-white" onClick={()=>attempt(()=>enterprise.openBusinessDay({requestId:crypto.randomUUID(),businessDate,actor:app.currentUser}),'تم فتح يوم العمل.')}>فتح يوم عمل</button></>}{day?.status==='closed'&&<button data-testid="reopen-business-day" className="rounded-xl bg-red-700 px-3 text-white" onClick={()=>app.requestManagerAuth('إعادة فتح يوم مغلق','إجراء استثنائي يتطلب سببًا واعتمادًا',true,(_n,reason,approval)=>attempt(()=>enterprise.reopenBusinessDay({businessDayId:day.id,reason,actor:app.currentUser,approval,persistenceHealthy:!persistenceIssue}),'تمت إعادة فتح يوم العمل.'),'business_day_reopen')}>إعادة فتح استثنائية</button>}<button onClick={()=>print()} className="rounded-xl border p-2"><Printer/></button></div></header>
 <div className="grid grid-cols-2 gap-3 lg:grid-cols-6">{cards.map(([k,v])=><div key={k} className="rounded-2xl border bg-white p-4"><small>{k}</small><b className="block">{money(v)}</b></div>)}</div>
 <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-3xl border bg-white p-5"><b>عد فئات النقدية</b><div className="mt-3 grid grid-cols-2 gap-2">{EGYPTIAN_DENOMINATIONS_PIASTRES.map(d=><label key={d} className="flex justify-between rounded-xl bg-slate-50 p-2 text-xs">{money(d)}<input className="w-20 border" type="number" min="0" value={qty[d]||''} onChange={e=>setQty(q=>({...q,[d]:Number(e.target.value)}))}/></label>)}</div><p className="mt-3 font-black">المعدود {money(count.totalPiastres)} — الفرق {money(count.differencePiastres)}</p><button className="mt-2 w-full rounded-xl bg-blue-700 p-2 text-white" onClick={()=>attempt(()=>{enterprise.saveCashCount({id:`cash-count-${day.id}`,businessDayId:day.id,shiftId:shifts[0]?.id,rows:count.rows,expectedPiastres:count.expectedPiastres,actor:app.currentUser})},'تم حفظ العد النقدي.')}>حفظ العد</button></section>
 <section className="space-y-4"><div className="rounded-3xl border bg-white p-5"><b>الإيداع الآمن</b><p className="text-xs text-slate-500">تحويل داخلي من الدرج إلى الخزينة الرئيسية.</p><div className="mt-3 flex gap-2"><input className="min-w-0 flex-1 border p-2" type="number" value={drop} onChange={e=>setDrop(e.target.value)} placeholder="المبلغ"/><button className="rounded-xl bg-amber-600 px-4 text-white" onClick={()=>attempt(()=>{if(!app.activeShift)throw new Error('لا توجد وردية مفتوحة.');enterprise.postSafeDrop({dropId:`${app.activeShift.id}-${Date.now()}`,shiftId:app.activeShift.id,amountPiastres:Math.round(Number(drop)*100),reason:'إيداع نقدية زائدة بالخزينة الرئيسية',actor:app.currentUser});setDrop('')},'تم التحويل الآمن.')}>تنفيذ</button></div></div><div className="rounded-3xl border bg-white p-5"><b>قائمة الإغلاق</b>{items.map(i=><label key={i.id} className="mt-2 flex gap-2 text-sm"><input type="checkbox" checked={done(i.id)} onChange={e=>enterprise.completeChecklistItem(day.id,i.id,e.target.checked,app.currentUser)}/>{i.label}{i.required&&<span className="text-red-600">*</span>}</label>)}</div></section></div>
 <section className="rounded-3xl border bg-white p-5"><h2 className="font-black"><ShieldAlert className="inline"/> جاهزية الإغلاق</h2>{blockers.map((b,i)=><div key={`${b.code}-${i}`} className="mt-2 rounded-xl bg-red-50 p-3 text-sm">{b.message} — <b>{b.actionTarget}</b></div>)}{!blockers.length&&<p className="mt-2 bg-emerald-50 p-3">جاهز للإغلاق.</p>}<button disabled={blockers.some(b=>b.severity==='critical')||day.status==='closed'} className="mt-4 w-full rounded-xl bg-slate-900 p-3 font-black text-white disabled:opacity-40" onClick={()=>attempt(()=>enterprise.closeBusinessDay({businessDayId:day.id,actor:app.currentUser,reconciliation:rec,shifts,journalEntries:journal()}),'تم الإغلاق وحفظ اللقطة غير القابلة للتعديل.')}>إغلاق يوم العمل وإنشاء اللقطة</button>{message&&<p className="mt-3 text-center font-bold">{message}</p>}</section>
 {enterprise.dailyCloseSnapshots.filter(s=>s.businessDayId===day.id).map(s=>{const r=s.reconciliation as typeof rec;return <section key={s.id} className="rounded-3xl border bg-white p-5 print:border-0"><div className="flex justify-between"><b>تقرير المالك اليومي — {s.businessDate}</b><span>أغلقه: {s.closedBy}</span></div><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4"><p>إجمالي البيع<br/><b>{money(r.sales.grossSalesPiastres)}</b></p><p>المرتجعات<br/><b>{money(r.sales.refundsPiastres)}</b></p><p>صافي البيع<br/><b>{money(r.sales.netSalesPiastres)}</b></p><p>المصروفات<br/><b>{money(r.expenses.totalPiastres)}</b></p><p>نقدي<br/><b>{money(r.payments.cashPiastres)}</b></p><p>بطاقات<br/><b>{money(r.payments.cardPiastres)}</b></p><p>InstaPay<br/><b>{money(r.payments.instapayPiastres)}</b></p><p>حالة المطابقة<br/><b>{r.status}</b></p></div><p className="mt-4 text-xs">رقم اللقطة: {s.id} — العملية: {s.operationId} — لا يعاد احتساب هذا التقرير من البيانات الحية.</p></section>})}</div>;
}
