'use client';

import React, { useMemo, useState } from 'react';
import { useAppStore } from '@/lib/store';
import { useEnterpriseStore } from '@/lib/enterprise-store';
import { calculateTax } from '@/lib/tax-engine';
import { Calculator, Plus, ReceiptText } from 'lucide-react';

const money=(p:number)=>`${(p/100).toLocaleString('ar-EG',{minimumFractionDigits:2})} ج`;
export default function TaxScreen(){
 const app=useAppStore(),e=useEnterpriseStore();const[name,setName]=useState('');const[code,setCode]=useState('');const[rate,setRate]=useState('');const[mode,setMode]=useState<'inclusive'|'exclusive'>('inclusive');
 const active=e.taxRules.find(x=>x.enabled);const report=useMemo(()=>{let gross=0,taxable=0,tax=0,refundTax=0;for(const o of app.orders.filter(x=>x.status!=='cancelled')){const grossPiastres=Math.round(o.total*100);const legacy=calculateTax(grossPiastres,active);const orderTax=o.taxAmount===undefined?legacy.tax:Math.round(o.taxAmount*100);const orderTaxable=o.taxableAmount===undefined?legacy.taxable:Math.round(o.taxableAmount*100);gross+=grossPiastres;taxable+=orderTaxable;tax+=orderTax;if(o.refundAmount&&o.total>0){refundTax+=Math.round(orderTax*(o.refundAmount/o.total));}}return{gross,taxable,tax,refundTax,netTax:tax-refundTax};},[app.orders,active]);
 const add=()=>{const percent=Number(rate);if(!name.trim()||!code.trim()||percent<0)return;e.addTaxRule({name,code,rateBasisPoints:Math.round(percent*100),mode,enabled:false,activeFrom:new Date().toISOString().slice(0,10),productIds:[],categoryIds:[]});setName('');setCode('');setRate('');};
 return <div className="space-y-5 bg-slate-100 p-6" dir="rtl"><div className="flex items-center gap-3 rounded-3xl border bg-white p-5"><div className="rounded-2xl bg-violet-50 p-3 text-violet-700"><Calculator/></div><div><h1 className="text-xl font-black">إعدادات وتقارير الضرائب</h1><p className="text-xs text-slate-500">لا توجد نسبة مفترضة؛ كل قاعدة تُضبط وتُفعّل يدويًا</p></div></div><div className="grid gap-4 lg:grid-cols-[380px_1fr]"><div className="space-y-3 rounded-3xl border bg-white p-5"><h2 className="flex items-center gap-2 font-black"><Plus className="h-4 w-4"/>قاعدة ضريبية</h2><input value={name} onChange={x=>setName(x.target.value)} placeholder="اسم الضريبة" className="w-full rounded-xl border p-3"/><input value={code} onChange={x=>setCode(x.target.value)} placeholder="الكود" className="w-full rounded-xl border p-3"/><input type="number" value={rate} onChange={x=>setRate(x.target.value)} placeholder="النسبة %" className="w-full rounded-xl border p-3"/><select value={mode} onChange={x=>setMode(x.target.value as typeof mode)} className="w-full rounded-xl border p-3"><option value="inclusive">شاملة السعر</option><option value="exclusive">تضاف على السعر</option></select><button onClick={add} className="w-full rounded-xl bg-[#0F52BA] p-3 text-sm font-black text-white">إضافة بدون تفعيل</button><div className="rounded-xl bg-amber-50 p-3 text-xs text-amber-900">تفعيل القاعدة قرار إداري لأنه يغيّر حساب الطلبات. الأسعار الحالية لا تتغير ما لم تُفعّل قاعدة.</div></div><div className="space-y-4"><div className="overflow-hidden rounded-3xl border bg-white"><div className="grid grid-cols-5 bg-slate-50 p-4 text-xs font-black"><span>الاسم</span><span>الكود</span><span>النسبة</span><span>الطريقة</span><span>التفعيل</span></div>{e.taxRules.map(r=><div key={r.id} className="grid grid-cols-5 border-t p-4 text-xs"><b>{r.name}</b><span>{r.code}</span><span>{r.rateBasisPoints/100}%</span><span>{r.mode==='inclusive'?'شاملة':'إضافية'}</span><button onClick={()=>e.updateTaxRule({...r,enabled:!r.enabled})} className={r.enabled?'font-bold text-emerald-700':'text-slate-500'}>{r.enabled?'مفعلة':'معطلة'}</button></div>)}</div><div className="rounded-3xl border bg-white p-5"><h2 className="mb-4 flex items-center gap-2 font-black"><ReceiptText className="h-4 w-4"/>ملخص ضريبي</h2><div className="grid grid-cols-2 gap-3 md:grid-cols-5">{[['إجمالي',report.gross],['خاضع',report.taxable],['الضريبة',report.tax],['أثر المرتجعات',-report.refundTax],['صافي الضريبة',report.netTax]].map(([l,v])=><div key={String(l)} className="rounded-xl bg-slate-50 p-3"><small>{l}</small><b className="mt-1 block">{money(Number(v))}</b></div>)}</div></div></div></div></div>;
}
